inicio/urls.py
from django.urls import path
from  inicio import views

urlpatterns = [
    path("",views.inicio, name="inicio"),
    path("About/",views.acercademi, name="acercademi"),
    path("segunda vista",views.segunda_vista, name="segunda_vista"),
    path("fecha_de_hoy/",views.fecha_de_hoy, name="fecha_de_hoy"),
    path("saludo/", views.saludo, name= "saludo"),
    path("bienvenido/<str:nombre>/<str:apellido>/", views.bienvenido, name= "saludar"),
    path("clientes/", views.Listaclientes.as_view(), name="lista_de_clientes"),
    path("cliente/crear/", views.CrearCliente.as_view(), name="craer_cliente"),
    path("cliente/eliminar/<int:pk>/", views.Eliminarcliente.as_view(), name="eliminar_cliente"),
    path("cliente/modificar/<int:pk>/", views.ModificarCliente.as_view(), name="modificar_cliente"),
    path("cliente/<int:pk>/", views.Descripciondelcliente.as_view(), name="descripcion_del_cliente"),
]

mi_primer_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", include("inicio.urls")),
    path("usuario/", include("usuario.urls")),
    path('admin/', admin.site.urls)

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuario/urls.py
from django.urls import path
from usuario import views
from django.contrib.auth.views import LogoutView

app_name= "usuario"

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', LogoutView.as_view(template_name="usuario/logout.html"), name='logout'),
    path('registro/', views.registrarse, name='registrarse'),
    path("usuario/", views.perfildelusario.as_view(), name='perfil_del_usuario'),
    path('perfil/editar/', views.edicion_de_perfil, name='edicion_de_perfil'),
    path('perfil/editar/password/', views.ModificarPass.as_view(), name='modificar_pass')
]

usuario/models.py
from django.db import models
from django.contrib.auth.models import User

class InfoExtra(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatares', null=True, blank=True)
    edad= models.CharField(null=True, max_length=20)  

usuario/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth import authenticate, login as django_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from usuario.form import MiFormalarioDeCreacionDeUsarios, MiFormularioDeEdicionDeDatosDeUsuario,buscarUsuarioformulario
from django.views.generic.list import ListView
from django.urls import reverse_lazy
from usuario.models import InfoExtra, User
from django.views.generic.detail import DetailView



def login(request):
    
    if request.method == 'POST':
        formulario = AuthenticationForm(request, data=request.POST)
        if formulario.is_valid():
            usuario = formulario.cleaned_data['username']
            contrasenia = formulario.cleaned_data['password']
            
            user = authenticate(username=usuario, password=contrasenia)
            
            django_login(request, user)
            
            InfoExtra.objects.get_or_create(user=user)
           
            
            return redirect('inicio')
        else:
            return render(request, 'usuario/login.html',  {'formulario': formulario})
            
    formulario = AuthenticationForm()
    return render(request, 'usuario/login.html',  {'formulario': formulario})
    # return render(request, "usuario/login.html")
    
def registrarse(request):
    
    if request.method == 'POST':
        formulario = MiFormalarioDeCreacionDeUsarios(request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect("usuario:login")
        else:
            return render(request, 'usuario/registrarse.html', {'formulario': formulario})


    formulario = MiFormalarioDeCreacionDeUsarios()
    return render(request, 'usuario/registrarse.html', {'formulario': formulario})


@login_required
def edicion_de_perfil(request):
    info_extra_user = request.user.infoextra
    if request.method == 'POST':
        formulario = MiFormularioDeEdicionDeDatosDeUsuario(request.POST, request.FILES, instance=request.user)
        if formulario.is_valid():
            
            avatar = formulario.cleaned_data.get('avatar')
            if avatar:
                info_extra_user.avatar = avatar
                
            edad = formulario.cleaned_data.get('edad')
            if edad:
                info_extra_user.edad = edad
            
            info_extra_user.save()
            
            formulario.save()
            return redirect('inicio')
    else:
        formulario = MiFormularioDeEdicionDeDatosDeUsuario(initial={'avatar': info_extra_user.avatar, 'edad': info_extra_user.edad}, instance=request.user)
        
    return render(request, 'usuario/edicion_de_perfil.html', {'formulario': formulario})


class ModificarPass(LoginRequiredMixin,PasswordChangeView):
    template_name= "usuario/modificar_pass.html"
    success_url = reverse_lazy('usuario:edicion_de_perfil')
    
    
class perfildelusario(ListView):
    # model = Cliente
    # template_name = "inicio/CBV/lista_de_cliente_CBV.html"
    # context_object_name="clientes"
    model =InfoExtra
    template_name = "usuario/perfil_del_usuario.html"
    context_object_name = 'usuario'
    def get_queryset(self):
        listado_de_usuarios= []
        formulario = buscarUsuarioformulario(self.request.GET)
        if formulario.is_valid():
            nombre_a_buscar = formulario.cleaned_data['Nombre']
            users = User.objects.filter(first_name__icontains=nombre_a_buscar)
            listado_de_usuarios = InfoExtra.objects.filter(user_id__in=users.values("id"))
        return listado_de_usuarios
    
    
# class PerfilDelUsario(DetailView):
#     model =InfoExtra
#     template_name = "usuario/perfil_del_cliente.html"
    

usuario/templates/usuario/edicion_de_perfil.html
{% extends 'base.html' %}

{% block title_head %}
<title>Edicion perfil</title>
{% endblock title_head %}

{% block h1_header %}
Editar perfil
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'usuario:edicion_de_perfil' %} method="post" enctype='multipart/form-data'>
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Guardar cambios</button>
    <button type='button'><a class="navbar-brand" href={% url 'usuario:modificar_pass' %}>Cambiar contrasenia</a></button>
</form>
{% comment %} <form action={% url 'usuario:editar_perfil' %} method="post" enctype='multipart/form-data'>
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Guardar cambios</button>
    <button type='button'><a class="navbar-brand" href={% url 'usuario:modificar_pass' %}>Cambiar contrasenia</a></button>
</form> {% endcomment %}
{% endblock contenido %}

usuario/templates/usuario/login.html
{% extends 'base.html' %}

{% block title_head %}
<title>Login</title>
{% endblock title_head %}

{% block h1_header %}
Login
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'usuario:login' %} method="POST">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Login</button>
</form>
{% endblock contenido %}

usuario/templates/usuario/logout.html
{% extends 'base.html' %}

{% block title_head %}
<title>logout</title>
{% endblock title_head %}

{% block h1_header %}
te deslogueaste con exito!
{% endblock h1_header %}

{% block contenido %}

   
{% endblock contenido %}

usuario/templates/usuario/modificar_pass.html
{% extends 'base.html' %}

{% block title_head %}
<title>modificar pass</title>
{% endblock title_head %}

{% block h1_header %}
modificar pass
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'usuario:modificar_pass' %} method="post" enctype='multipart/form-data'>
    {% csrf_token %}
    <table>
        {{form}}
    </table>
    <button>Cambiar Contrasenia</button>
{% endblock contenido %}

usuario/templates/usuario/perfil_del_usuario.html
{% extends 'base.html' %}

{% block  title_head %}
<title>usario</title>
{% endblock  %}

{% block h1_header %}
    {{request.user.username}}
{% endblock h1_header %}

{% block contenido %}

    <li>
        <p>Nombre de usuario: {{request.user.username}} </p>
        <p>Nombre: {{request.user.first_name}} </p>
        <p>Apellido: {{request.user.last_name}}</p>
        <button>
            <a class="navbar-brand" href={% url "usuario:edicion_de_perfil" %}>editar usario</a>
        </button>
    </li>    
 
    
{% endblock  %}

usuario/templates/usuario/registrarse.html
{% extends 'base.html' %}

{% block title_head %}
<title>Registrarse</title>
{% endblock title_head %}

{% block h1_header %}
Registro
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'usuario:registrarse' %} method="POST">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Resgistrar cuenta</button>
</form>
{% endblock contenido %}