inicio/urls.py
from django.urls import path
from  inicio import views

urlpatterns = [
    path("",views.inicio, name="inicio"),
    path("About/",views.acercademi, name="acercademi"),
    path("segunda vista",views.segunda_vista, name="segunda_vista"),
    path("fecha_de_hoy/",views.fecha_de_hoy, name="fecha_de_hoy"),
    path("saludo/", views.saludo, name= "saludo"),
    path("bienvenido/<str:nombre>/<str:apellido>/", views.bienvenido, name= "saludar"),
    path("clientes/", views.Listaclientes.as_view(), name="lista_de_clientes"),
    path("cliente/crear/", views.CrearCliente.as_view(), name="craer_cliente"),
    path("cliente/eliminar/<int:pk>/", views.Eliminarcliente.as_view(), name="eliminar_cliente"),
    path("cliente/modificar/<int:pk>/", views.ModificarCliente.as_view(), name="modificar_cliente"),
    path("cliente/<int:pk>/", views.Descripciondelcliente.as_view(), name="descripcion_del_cliente"),
]

mi_primer_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", include("inicio.urls")),
    path("usuario/", include("usuario.urls")),
    path('admin/', admin.site.urls)

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuario/urls.py
from django.urls import path
from usuario import views
from django.contrib.auth.views import LogoutView

app_name= "usuario"

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', LogoutView.as_view(template_name="usuario/logout.html"), name='logout'),
    path('registro/', views.registrarse, name='registrarse'),
    path("usuario/", views.perfildelusario.as_view(), name='perfil_del_usuario'),
    path('perfil/editar/', views.edicion_de_perfil, name='edicion_de_perfil'),
    path('perfil/editar/password/', views.ModificarPass.as_view(), name='modificar_pass')
]

inicio/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.
class Cliente(models.Model):
    nombre = models.CharField(max_length=20)
    edad= models.IntegerField()
    fecha= models.DateTimeField(null=True)
    nacionalidad = models.CharField(max_length=20, blank=True, null=True)
    descripcion= RichTextField(null=True)
    imagen = models.ImageField(upload_to='imagen', null=True, blank=True)
    
    def __str__(self):
        return f"Cliente: {self.nombre} - Edad : {self.edad} - Nacionalidad: {self.nacionalidad}"

inicio/views.py
from django.shortcuts import render
from django.http import HttpResponse
from datetime import datetime
from django.template import Template, Context, loader
from inicio.models import Cliente
from django.shortcuts import render, redirect
from inicio.form import Crearclienteformulario, buscarclienteformulario, modificarclienteformulario, clienteformulariobase
from django.views.generic.edit import CreateView, UpdateView,DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
def inicio(request):
    return render(request,"inicio/inicio.html")

def acercademi(request):
    return render(request,"inicio/acerca_de_mi.html")

def prueba(request):
    
    
    segundos = datetime.now().second
    diccionario={
        "mensaje": "este es el mensaje de inicio",
        "segundos" : segundos ,
        "segundos_par": segundos%2 == 0 ,
        "segundo_redondo":segundos %10 == 0 ,
        "listado_segundos": list(range(25))
    }
    return render(request, "inicio/prueba.html", diccionario)

    # segundos = datetime.now().second
    # diccionario={
    #     "mensaje": "este es el mensaje de inicio",
    #     "segundos" : segundos ,
    #     "segundos_par": segundos%2 == 0 ,
    #     "segundo_redondo":segundos %10 == 0 ,
    #     "listado_segundos": list(range(25))
    # }
    # return render(request, "inicio/prueba.html", diccionario)



def segunda_vista(request):
    return HttpResponse("<h1>soy la segunda vista</h1>")

@login_required
def fecha_de_hoy(request):
    fecha= datetime.now()
    return HttpResponse(f"fecha actual {fecha}")


def saludo(request):
    return HttpResponse("bienvenido")


def bienvenido(request, nombre , apellido):
    return HttpResponse(f"bienvenido {nombre.title()}, {apellido.title()}")

            
            
    # formulario = Crearclienteformulario()
    # return render(request, "inicio/crear_cliente.html",  {"formulario": formulario})


class CrearCliente(CreateView,LoginRequiredMixin):
    model= Cliente
    template_name= "inicio/CBV/crear_cliente_CBV.html"
    fields= ["nombre", "edad", "nacionalidad", "descripcion","imagen","fecha"]
    success_url= reverse_lazy("lista_de_clientes")
    
class Listaclientes(ListView):
    # model = Cliente
    # template_name = "inicio/CBV/lista_de_cliente_CBV.html"
    # context_object_name="clientes"
    model =Cliente
    template_name = "inicio/CBV/lista_de_cliente_CBV.html"
    context_object_name = 'clientes'
    def get_queryset(self):
        listado_de_clientes= []
        formulario = buscarclienteformulario(self.request.GET)
        if formulario.is_valid():
            nombre_a_buscar = formulario.cleaned_data['nombre']
            listado_de_clientes = Cliente.objects.filter(nombre__icontains=nombre_a_buscar)
        return listado_de_clientes
    
    
    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['formulario'] = buscarclienteformulario()
        return contexto
    
    
    
   
    
    
class ModificarCliente(LoginRequiredMixin,UpdateView):
    model = Cliente
    template_name = "inicio/CBV/modificar_cliente_CBV.html"
    fields= ["nombre", "edad", "nacionalidad", "descripcion","imagen","fecha"]
    # form_class = clienteformulariobase
    success_url= reverse_lazy("lista_de_clientes")
    
    def form_valid(self, form):
        instance = form.save(commit=False)
        if form.cleaned_data['imagen']:
            instance.imagen = form.cleaned_data['imagen']
        instance.save()
        return super().form_valid(form)
    

class Eliminarcliente(LoginRequiredMixin,DeleteView):
    model = Cliente
    template_name = "inicio/CBV/eliminar_cliente_CBV.html"
    success_url= reverse_lazy("lista_de_clientes")
    
class Descripciondelcliente(DetailView):
    model = Cliente
    template_name = "inicio/CBV/descripcion_del_cliente_CBV.html"
    
# def login(request):
#     return render(request,"template", {})    

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% block title_head %}
        <title>Template Base</title>
        {% endblock title_head %}
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static 'css/styles.css' %} rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href={% url 'inicio' %}>Inicio</a>
                <a class="navbar-brand" href={% url 'lista_de_clientes' %}>clientes</a>
                {% comment %} <a class="navbar-brand" href={% url 'usuario: login' %}>login</a> {% endcomment %}
                {% if request.user.is_authenticated %}
                {% if request.user.infoextra.avatar %}
                <img src={{request.user.infoextra.avatar.url}} alt="" height='40px'>
                {% endif %}
                {% comment %} <a class="navbar-brand" href={% url 'usuario:perfil_del_cliente' %}>{{request.user.username}}</a> {% endcomment %}
                <a class="navbar-brand" href={% url 'usuario:perfil_del_usuario' %}>{{request.user.username}}</a>
                <a class="navbar-brand" href={% url 'usuario:logout' %}>logout</a>
                {% else %}
                <a class="navbar-brand" href={% url 'usuario:login' %}>login</a>
                <a class="navbar-brand" href={% url 'usuario:registrarse' %}>registrarse</a>
                {% endif %}
            </div>
        </nav>

        {% block header %}
        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            <h1 class="mb-5">
                                {% block h1_header %}
                                Nuestra web intermedia de Django - Coderhouse
                                {% endblock h1_header %}
                            </h1>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock header %}

        {% block contenido %}
        <p></p>
        {% endblock contenido %}

        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href={% url 'acercademi' %}>About</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Contact</a></li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2023. All Rights Reserved.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>
                
                

templates/inicio.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>este es mi primer template que cree</h1>
    <p>{{mensaje}}</p>
    <p>{{segundos}}</p>
    {% if segundo_redondo %}
    <p style="color: red;">{{segundos}}</p> 
    {% elif segundos_par %}
    <p style="color: green;">{{segundos}}</p> 
    {% else %}
    <p style="color: blue ;">{{segundos}}</p> 
    {% endif %}
    {%for numero in listado_segundos%}
    <p>{{numero}}</p>
    {% endfor%}
</body>
</html>